export const CURATED_ARTIST_PROFILES = [
  {
    name: "Amelia Presley",
    bio: "Amelia Presley is an Americana singer-songwriter with Gulf Coast roots and a sound that blends country, Southern rock, and blues. Her emotionally direct songwriting is shaped by family, hard-earned life experience, and the musical traditions she grew up around.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Andrew Wooten",
    bio: "Andrew Wooten is a Marine veteran and alternative-country artist from South Carolina whose music blends Southern rock, country, and Appalachian influence. After more than 15 years of performing, he has shared stages with artists including Sammy Kershaw, Aaron Tippin, Tennessee Jet, and The Kentucky Headhunters.",
    stations: ["semper-fi-country"],
    website: "https://andrewwooten.net/",
  },
  {
    name: "Barbara Sim",
    bio: "Barbara Sim is a singer-songwriter, van-lifer, and U.S. Marine Corps veteran. Her music is rooted in honest storytelling and the experiences that have shaped her life on and off the road.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Billy Ray Wheaton",
    bio: "Billy Ray Wheaton is a veteran singer-songwriter who draws on life as a service member, husband, father, and son. His country music is built around direct storytelling, lived experience, and emotional authenticity.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Brandon Mills",
    bio: "Brandon Mills is a Nashville-based singer-songwriter and Special Forces veteran whose music blends folk, pop, blues, and Americana. His songs focus on connection, purpose, and the perspective gained through service and life experience.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Briella Steiner",
    bio: "Briella Steiner is an independent singer-songwriter and the daughter of a Marine veteran. Her work brings a military-family connection to a growing catalog of original music and a developing career as an independent artist.",
    stations: ["semper-fi-country"],
    website: "https://briellasteiner.com/",
  },
  {
    name: "Chuck Briseno",
    bio: "Chuck Briseno is a Texas-born Red Dirt and country artist, U.S. Army veteran, and full-time touring musician. His songs combine Texas grit, Americana soul, and road-worn storytelling.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Chuck Wimer",
    bio: "Chuck Wimer is a U.S. Army veteran and country artist whose music blends traditional country, Americana, and alt-country influences. His songs center on love, loss, redemption, family, and the values carried from military service into civilian life.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Cody Howell",
    bio: "Cody Howell is a Navy veteran and country singer-songwriter who brought his music to Nashville after military service. His sound draws from modern country while keeping a strong connection to traditional songwriting and live performance.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Collie To Congress",
    bio: "Collie To Congress is an independent country project led by a U.S. Army Warrant Officer. The music pairs patriotic and everyday American themes with an independent, personality-driven approach to songwriting.",
    stations: ["semper-fi-country"],
    website: "https://artists.landr.com/991043540199",
  },
  {
    name: "Dan Wesley White",
    bio: "Dan Wesley White is a Texas singer-songwriter, U.S. Army veteran, and former Army Band musician who later became a music educator. His songs blend country with Tex-Mex, Texas swing, and rock influences, including work that raises awareness of veteran suicide.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Derek Stoner",
    bio: "Derek Stoner is a country artist who launched his music career after retiring from a 20-year U.S. Army Special Forces career. A fixture of Nashville honky-tonks, he brings a powerful vocal style shaped by the 1990s country music he grew up on.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Derek Thompson",
    bio: "Derek Thompson is a former U.S. Marine and firefighter who performs as part of L&T Music. His work pairs veteran perspective with a collaborative country sound built around vocals, guitar, and independent songwriting.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Duane Parker",
    bio: "Duane Parker is a Blue Ridge Mountains-raised country singer-songwriter and the son of a Vietnam veteran. A longtime honky-tonk performer influenced by Waylon Jennings, Willie Nelson, Johnny Cash, Merle Haggard, and David Allan Coe, he has opened for artists including T. Graham Brown, Gene Watson, Neal McCoy, and the Marshall Tucker Band.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Duke Henry",
    bio: "Duke Henry is an outlaw-country and Southern-rock singer, songwriter, guitarist, and entertainer with Duke Henry and Mercy Road Station. His story-driven songs mix classic-country roots with a modern full-band sound.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Gamble Alexander",
    bio: "Gamble Alexander is a U.S. Marine Corps veteran, independent musician, singer, and songwriter. His work reflects the direct, personal storytelling at the heart of independent country music.",
    stations: ["semper-fi-country"],
  },
  {
    name: "High Pines",
    bio: "High Pines is an independent band featuring Sam Mamary, Rob Doran, Sam Pipp, and Brian Larose. Their music brings a roots-oriented band sound to the Semper Fi Country lineup.",
    stations: ["semper-fi-country"],
  },
  {
    name: "JB Brown",
    bio: "JB Brown is a country artist and medically retired U.S. Marine who served 12 years, including combat operations in Iraq. After years in Southern California's rock scene, he returned to the country influences he grew up with and now tours with the JB Brown Band.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Jenn Ford",
    bio: "Jenn Ford is an East Texas singer-songwriter and U.S. Army veteran whose military music career included the Army Soldier Show, the 62nd Army Band, and the U.S. Army Europe Band and Chorus. Her sound mixes country, blues, Southern rock, and the stage experience of performing for military audiences around the world.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Jeremiah Bones",
    bio: "Jeremiah Bones is an Army veteran and independent country artist. His songwriting brings veteran perspective and a stripped-down, roots-driven approach to the Semper Fi Country catalog.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Jim Hoehn",
    bio: "Jim Hoehn is a journalist, author, songwriter, and performing artist whose recordings have received Americana, folk, and alt-country airplay in the U.S. and abroad. He has opened for artists including John Hiatt, Rodney Crowell, Jerry Jeff Walker, Robert Earl Keen, Roger McGuinn, and Todd Snider. VVR has not yet verified a military-service connection for Jim.",
    stations: ["semper-fi-country"],
    website: "https://jimhoehn.com/",
  },
  {
    name: "Joe Allen Christi",
    bio: "Joe Allen Christi is a Texas country artist and 24-year U.S. Air Force veteran from South Texas. His music blends classic-country storytelling with Texas-country energy and themes of faith, family, heartbreak, redemption, and home.",
    stations: ["semper-fi-country"],
    website: "https://joeallenchristi.com/",
  },
  {
    name: "John Hensley",
    bio: "John Hensley is an Army veteran and singer-songwriter whose service included Army airfield operations and a deployment to Iraq. His music carries that life experience into an independent country setting.",
    stations: ["semper-fi-country"],
  },
  {
    name: "John Swat",
    displayName: "John ‘SWAT’ Swantner",
    bio: "John ‘SWAT’ Swantner is an Iraq War veteran from Bellville, Texas whose nickname was given to him by fellow soldiers. He performed for troops overseas and later built a Nashville songwriting career around a blend of traditional and modern country, working with established writers and artists along the way.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Josh Davis",
    bio: "Josh Davis is a combat-disabled U.S. Army veteran and outlaw-country singer-songwriter based in Florida. His music leans into raw storytelling, blues influence, and the independent spirit of classic outlaw country.",
    stations: ["semper-fi-country"],
    website: "https://therealjoshdavis.com/",
  },
  {
    name: "Jovon Newman",
    bio: "Jovon Newman is a Delaware Air National Guard member and singer-songwriter whose sound blends country, pop, and R&B. A viral cover helped introduce his voice to a wider audience, and his original music has continued to build recognition across the Mid-Atlantic region.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Kimberly Meyer",
    bio: "Kimberly Meyer is a singer-songwriter and officer in the South Dakota Army National Guard who began her service as a musician with the 147th Army Band. Her military and civilian music careers include years as a vocalist, instrumentalist, teacher, performer, and songwriter.",
    stations: ["semper-fi-country"],
    website: "https://www.kimberlymeyermusic.com/",
  },
  {
    name: "Michael Allen",
    bio: "Michael Allen is a U.S. Army veteran and former Green Beret who turned to songwriting after years of military service and combat deployments. His music explores war, survival, relationships, and the difficult work of finding peace after service.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Mike Ponder",
    bio: "Mike Ponder is a 20-year U.S. Navy veteran and lifelong musician with decades of live-performance experience. He has kept music at the center of his life through military service and into a country career based in Nashville.",
    stations: ["semper-fi-country"],
    website: "https://www.mikepondermusic.com/",
  },
  {
    name: "Nate Turner",
    bio: "Nate Turner is a 23-year military veteran and independent country artist from North Carolina. After surviving throat cancer and rebuilding his singing voice, he retired from the military in 2022 and began pursuing music full time with a mix of classic country, Southern rock, and original songs.",
    stations: ["semper-fi-country"],
    website: "https://n8turnermusic.com/",
  },
  {
    name: "Old 81 Band",
    bio: "Old 81 Band is a Red Dirt and country band with roots in the independent Texas and Oklahoma music scene. Band member Ryan Helm is a U.S. Marine Corps veteran, giving the group a direct veteran connection alongside its original country sound.",
    stations: ["semper-fi-country"],
    website: "https://legacy.reverbnation.com/old81band",
  },
  {
    name: "Rick Brown",
    bio: "Rick Brown is a U.S. veteran and independent country artist. His music brings a veteran voice and traditional country storytelling to the Semper Fi Country rotation.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Rowdy Johnson",
    bio: "Rowdy Johnson is a U.S. Navy veteran and outlaw-country singer-songwriter known for a traditional, hard-edged style rooted in real-life experience. His music and live work also reflect a strong commitment to supporting fellow veterans and the Armed Forces.",
    stations: ["semper-fi-country"],
    website: "https://rowdyjohnson.com/",
  },
  {
    name: "Rustic Ridge",
    bio: "Rustic Ridge is an Americana band featuring Denise, Chris, Mark, and Jim, with songs built around folklore, family history, lived experience, and darker roots storytelling. Guitarist Chris and drummer Mark served together in the U.S. Air Force in the early 1990s and were making music together even then.",
    stations: ["semper-fi-country"],
    website: "https://www.rusticridgemusic.com/",
  },
  {
    name: "Sal Gonzalez",
    bio: "Sal Gonzalez is a U.S. Marine Corps combat veteran, singer-songwriter, and wounded warrior who was injured by an IED while serving in Iraq. Music became a major part of his recovery and later carried him to national television and the Grand Ole Opry stage.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Schaefer Mueller",
    bio: "Schaefer Mueller is an Army combat veteran and singer-songwriter from Virginia whose music blends country with a broad range of American roots influences. He has performed across the country and opened for artists including Chris Young and Granger Smith.",
    stations: ["semper-fi-country"],
    website: "https://www.schaefermueller.com/",
  },
  {
    name: "Scotti Fraser",
    bio: "Scotti Fraser is a U.S. Marine Corps combat veteran and Texas singer-songwriter whose Americana sound blends country and rock. His music draws heavily from military service, hardship, PTSD awareness, resilience, and a mission of leaving listeners with hope.",
    stations: ["semper-fi-country"],
    website: "https://www.scottifraser.com/",
  },
  {
    name: "Scotty Hasting",
    bio: "Scotty Hasting is a U.S. Army combat veteran, Purple Heart recipient, and country artist. After being wounded in Afghanistan, he found a new path through music and now uses songwriting and performance to connect with and support other veterans.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Stephen Covell",
    bio: "Stephen Covell is an Army veteran, former combat medic, singer-songwriter, writer, and illustrator who served with the 82nd Airborne Division and deployed to Iraq. His songs often function as short stories about service, memory, identity, and the long road home.",
    stations: ["semper-fi-country"],
    website: "https://www.stephencovell.com/",
  },
  {
    name: "Sugar Rose",
    bio: "Sugar Rose is a military spouse and independent country artist whose music brings the military-family perspective into the Semper Fi Country lineup. Her work reflects the broader community of service members, veterans, and families VVR was built to support.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Therasa Donefire",
    displayName: "Theresa Denofre",
    bio: "Theresa Denofre is a singer-songwriter who performed with Operation Encore while serving in the U.S. Air Force. Her song ‘Your Lullaby’ appeared on Operation Encore's first veteran-music compilation, connecting her music directly to the military creative community.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Tim Newton",
    bio: "Tim Newton is an Army National Guard member and independent country singer-songwriter. His original songs bring a grounded, everyday-country perspective to Semper Fi Country.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Tom Nitti",
    bio: "Tom Nitti is a U.S. Army veteran, Purple Heart recipient, and country singer-songwriter. His music career reflects both his military experience and a commitment to traditional, story-driven country performance.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Travis Walker",
    bio: "Travis Walker is a U.S. Army veteran from Greenville, South Carolina who served as a combat engineer with the 1st Infantry Division at Fort Riley. A lifelong singer, he brings faith, family, country roots, and military service into his music.",
    stations: ["semper-fi-country"],
    website: "https://traviswalkermusic.com/",
  },
  {
    name: "War Hippies",
    bio: "War Hippies is the country duo of Marine veteran Scooter Brown and Army veteran Donnie Reis, both combat veterans of the Iraq War. Their music combines Brown's country-rock background with Reis' multi-instrumental musicianship and a shared commitment to veterans and authentic storytelling.",
    stations: ["semper-fi-country"],
  },
  {
    name: "Winter Grain",
    bio: "Winter Grain is an Americana act built around roots songwriting and harmony. The group has a direct military connection through Kate, a retired U.S. Army helicopter pilot, bringing a veteran voice into its story-driven sound.",
    stations: ["semper-fi-country"],
  },
];
